const tokenBalanceABI = [
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"tokenURI",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"addr",
             "type":"address"
          }
       ],
       "name":"getTokens",
       "outputs":[
          {
             "internalType":"uint256[]",
             "name":"",
             "type":"uint256[]"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    }
 ]